[2023-10-14T11:07:30.032+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data.bash_task_to_run_ingester scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-10-14T11:07:30.132+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data.bash_task_to_run_ingester scheduled__2023-01-08T00:00:00+00:00 [queued]>
[2023-10-14T11:07:30.162+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-14T11:07:30.336+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): bash_task_to_run_ingester> on 2023-01-08 00:00:00+00:00
[2023-10-14T11:07:30.363+0000] {standard_task_runner.py:57} INFO - Started process 284 to run task
[2023-10-14T11:07:30.404+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'bash_task_to_run_ingester', 'scheduled__2023-01-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/ingester_dag.py', '--cfg-path', '/tmp/tmp985d148g']
[2023-10-14T11:07:30.424+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask bash_task_to_run_ingester
[2023-10-14T11:07:30.681+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_data.bash_task_to_run_ingester scheduled__2023-01-08T00:00:00+00:00 [running]> on host 7bc11bbfab2f
[2023-10-14T11:07:31.078+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibora' AIRFLOW_CTX_DAG_ID='ingest_data' AIRFLOW_CTX_TASK_ID='bash_task_to_run_ingester' AIRFLOW_CTX_EXECUTION_DATE='2023-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-08T00:00:00+00:00'
[2023-10-14T11:07:31.099+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-14T11:07:31.107+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 data_ingester.py --file_path="../data/20181029_d8_0800_0830.csv"']
[2023-10-14T11:07:31.283+0000] {subprocess.py:86} INFO - Output:
[2023-10-14T11:07:31.902+0000] {subprocess.py:93} INFO - python3: can't open file 'data_ingester.py': [Errno 2] No such file or directory
[2023-10-14T11:07:31.915+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-14T11:07:31.944+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-14T11:07:31.962+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data, task_id=bash_task_to_run_ingester, execution_date=20230108T000000, start_date=20231014T110730, end_date=20231014T110731
[2023-10-14T11:07:32.046+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task bash_task_to_run_ingester (Bash command failed. The command returned a non-zero exit code 2.; 284)
[2023-10-14T11:07:32.120+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-14T11:07:32.163+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
