[2023-10-14T11:07:30.038+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data.bash_task_to_run_ingester scheduled__2023-01-11T00:00:00+00:00 [queued]>
[2023-10-14T11:07:30.133+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data.bash_task_to_run_ingester scheduled__2023-01-11T00:00:00+00:00 [queued]>
[2023-10-14T11:07:30.138+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-14T11:07:30.183+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): bash_task_to_run_ingester> on 2023-01-11 00:00:00+00:00
[2023-10-14T11:07:30.224+0000] {standard_task_runner.py:57} INFO - Started process 282 to run task
[2023-10-14T11:07:30.229+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'bash_task_to_run_ingester', 'scheduled__2023-01-11T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/ingester_dag.py', '--cfg-path', '/tmp/tmpulkd76le']
[2023-10-14T11:07:30.242+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask bash_task_to_run_ingester
[2023-10-14T11:07:30.548+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_data.bash_task_to_run_ingester scheduled__2023-01-11T00:00:00+00:00 [running]> on host 7bc11bbfab2f
[2023-10-14T11:07:30.820+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibora' AIRFLOW_CTX_DAG_ID='ingest_data' AIRFLOW_CTX_TASK_ID='bash_task_to_run_ingester' AIRFLOW_CTX_EXECUTION_DATE='2023-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-11T00:00:00+00:00'
[2023-10-14T11:07:30.824+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-14T11:07:30.831+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 data_ingester.py --file_path="../data/20181029_d8_0800_0830.csv"']
[2023-10-14T11:07:30.877+0000] {subprocess.py:86} INFO - Output:
[2023-10-14T11:07:31.302+0000] {subprocess.py:93} INFO - python3: can't open file 'data_ingester.py': [Errno 2] No such file or directory
[2023-10-14T11:07:31.323+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-14T11:07:31.350+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-14T11:07:31.363+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data, task_id=bash_task_to_run_ingester, execution_date=20230111T000000, start_date=20231014T110730, end_date=20231014T110731
[2023-10-14T11:07:31.516+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task bash_task_to_run_ingester (Bash command failed. The command returned a non-zero exit code 2.; 282)
[2023-10-14T11:07:31.552+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-14T11:07:31.643+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
